//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressiveWeb.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressiveWeb.Localization.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poser une question....
        /// </summary>
        public static string CommunityAskQuestion {
            get {
                return ResourceManager.GetString("CommunityAskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre des développeurs.
        /// </summary>
        public static string CommunityDevCenter {
            get {
                return ResourceManager.GetString("CommunityDevCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un avis....
        /// </summary>
        public static string CommunitySendFeedback {
            get {
                return ResourceManager.GetString("CommunitySendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couper.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string DeleteElement {
            get {
                return ResourceManager.GetString("DeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masquer automatiquement.
        /// </summary>
        public static string DockAutoHide {
            get {
                return ResourceManager.GetString("DockAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer tous les onglets.
        /// </summary>
        public static string DockCloseAll {
            get {
                return ResourceManager.GetString("DockCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer les onglets à gauche.
        /// </summary>
        public static string DockCloseOnLeft {
            get {
                return ResourceManager.GetString("DockCloseOnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer les onglets à droite.
        /// </summary>
        public static string DockCloseOnRight {
            get {
                return ResourceManager.GetString("DockCloseOnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer les autres onglets.
        /// </summary>
        public static string DockCloseOthers {
            get {
                return ResourceManager.GetString("DockCloseOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string DockCloseTab {
            get {
                return ResourceManager.GetString("DockCloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détacher le panneau.
        /// </summary>
        public static string DockFloat {
            get {
                return ResourceManager.GetString("DockFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détacher le groupe de panneaux.
        /// </summary>
        public static string DockFloatAll {
            get {
                return ResourceManager.GetString("DockFloatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau groupe d&apos;onglets horizontal.
        /// </summary>
        public static string DockNewHorizontalGroup {
            get {
                return ResourceManager.GetString("DockNewHorizontalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau groupe d&apos;onglets vertical.
        /// </summary>
        public static string DockNewVerticalGroup {
            get {
                return ResourceManager.GetString("DockNewVerticalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupliquer.
        /// </summary>
        public static string DuplicateElement {
            get {
                return ResourceManager.GetString("DuplicateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string ExitApplication {
            get {
                return ResourceManager.GetString("ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre 1.
        /// </summary>
        public static string FormatHeading1 {
            get {
                return ResourceManager.GetString("FormatHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre 2.
        /// </summary>
        public static string FormatHeading2 {
            get {
                return ResourceManager.GetString("FormatHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre 3.
        /// </summary>
        public static string FormatHeading3 {
            get {
                return ResourceManager.GetString("FormatHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre 4.
        /// </summary>
        public static string FormatHeading4 {
            get {
                return ResourceManager.GetString("FormatHeading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre 5.
        /// </summary>
        public static string FormatHeading5 {
            get {
                return ResourceManager.GetString("FormatHeading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre 6.
        /// </summary>
        public static string FormatHeading6 {
            get {
                return ResourceManager.GetString("FormatHeading6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraphe.
        /// </summary>
        public static string FormatParagraph {
            get {
                return ResourceManager.GetString("FormatParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecté.
        /// </summary>
        public static string IsConnected {
            get {
                return ResourceManager.GetString("IsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hors ligne.
        /// </summary>
        public static string IsDisconnected {
            get {
                return ResourceManager.GetString("IsDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothèque.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string LibraryImages {
            get {
                return ResourceManager.GetString("LibraryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palettes.
        /// </summary>
        public static string LibraryPalettes {
            get {
                return ResourceManager.GetString("LibraryPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string LibraryStyles {
            get {
                return ResourceManager.GetString("LibraryStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos d&apos;Expressive Web....
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communauté.
        /// </summary>
        public static string MenuCommunity {
            get {
                return ResourceManager.GetString("MenuCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string MenuFormat {
            get {
                return ResourceManager.GetString("MenuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion.
        /// </summary>
        public static string MenuInsert {
            get {
                return ResourceManager.GetString("MenuInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau....
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet....
        /// </summary>
        public static string MenuNewProject {
            get {
                return ResourceManager.GetString("MenuNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenêtre.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer un cran après.
        /// </summary>
        public static string MoveElementAfter {
            get {
                return ResourceManager.GetString("MoveElementAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer un cran avant.
        /// </summary>
        public static string MoveElementBefore {
            get {
                return ResourceManager.GetString("MoveElementBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer au début.
        /// </summary>
        public static string MoveElementFirst {
            get {
                return ResourceManager.GetString("MoveElementFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer à la fin.
        /// </summary>
        public static string MoveElementLast {
            get {
                return ResourceManager.GetString("MoveElementLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier....
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page....
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier projet cible:.
        /// </summary>
        public static string NewProjectFilePath {
            get {
                return ResourceManager.GetString("NewProjectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser le Kit:.
        /// </summary>
        public static string NewProjectKit {
            get {
                return ResourceManager.GetString("NewProjectKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut de connexion.
        /// </summary>
        public static string OnlineStatus {
            get {
                return ResourceManager.GetString("OnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre site web peut avoir besoin de ressources distantes pour s&apos;afficher correctement. Vous pouvez cependant demander à ce que l&apos;application ne télécharge aucun élément distant pendant que vous travaillez..
        /// </summary>
        public static string OnlineStatusDescription {
            get {
                return ResourceManager.GetString("OnlineStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travailler hors ligne.
        /// </summary>
        public static string OnlineStatusOfflineRequired {
            get {
                return ResourceManager.GetString("OnlineStatusOfflineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de fichier.
        /// </summary>
        public static string PageFileName {
            get {
                return ResourceManager.GetString("PageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle de page.
        /// </summary>
        public static string PageTemplate {
            get {
                return ResourceManager.GetString("PageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coller.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refaire.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner tout.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le parent.
        /// </summary>
        public static string SelectParentElement {
            get {
                return ResourceManager.GetString("SelectParentElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur la **touche ctrl** pour dupliquer l&apos;objet lors du déplacement..
        /// </summary>
        public static string StatusPressCtrlToDropCopy {
            get {
                return ResourceManager.GetString("StatusPressCtrlToDropCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt..
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistré.
        /// </summary>
        public static string StatusSaved {
            get {
                return ResourceManager.GetString("StatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement en cours....
        /// </summary>
        public static string StatusSaving {
            get {
                return ResourceManager.GetString("StatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Cliquez une fois** sur les objets pour les sélectionner. **Cliquez deux fois** pour éditer les objets compatibles..
        /// </summary>
        public static string StatusSelectMessage {
            get {
                return ResourceManager.GetString("StatusSelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une nouvelle page....
        /// </summary>
        public static string TitleCreatePage {
            get {
                return ResourceManager.GetString("TitleCreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau projet....
        /// </summary>
        public static string TitleCreateProject {
            get {
                return ResourceManager.GetString("TitleCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;action prend plus de temps, veuillez patienter....
        /// </summary>
        public static string VariableDurationActionMessage {
            get {
                return ResourceManager.GetString("VariableDurationActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer tous les documents.
        /// </summary>
        public static string ViewCloseAllDocuments {
            get {
                return ResourceManager.GetString("ViewCloseAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer le document actif.
        /// </summary>
        public static string ViewCloseCurrentDocument {
            get {
                return ResourceManager.GetString("ViewCloseCurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer les documents à gauche.
        /// </summary>
        public static string ViewCloseDocumentsLeft {
            get {
                return ResourceManager.GetString("ViewCloseDocumentsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer les documents à droite.
        /// </summary>
        public static string ViewCloseDocumentsRight {
            get {
                return ResourceManager.GetString("ViewCloseDocumentsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer les autres documents.
        /// </summary>
        public static string ViewCloseOtherDocuments {
            get {
                return ResourceManager.GetString("ViewCloseOtherDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une commande....
        /// </summary>
        public static string WatermarkFilterCommands {
            get {
                return ResourceManager.GetString("WatermarkFilterCommands", resourceCulture);
            }
        }
    }
}
