//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressiveWeb.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressiveWeb.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask question....
        /// </summary>
        public static string CommunityAskQuestion {
            get {
                return ResourceManager.GetString("CommunityAskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer center.
        /// </summary>
        public static string CommunityDevCenter {
            get {
                return ResourceManager.GetString("CommunityDevCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback....
        /// </summary>
        public static string CommunitySendFeedback {
            get {
                return ResourceManager.GetString("CommunitySendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteElement {
            get {
                return ResourceManager.GetString("DeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string DuplicateElement {
            get {
                return ResourceManager.GetString("DuplicateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitApplication {
            get {
                return ResourceManager.GetString("ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 1.
        /// </summary>
        public static string FormatHeading1 {
            get {
                return ResourceManager.GetString("FormatHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 2.
        /// </summary>
        public static string FormatHeading2 {
            get {
                return ResourceManager.GetString("FormatHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 3.
        /// </summary>
        public static string FormatHeading3 {
            get {
                return ResourceManager.GetString("FormatHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 4.
        /// </summary>
        public static string FormatHeading4 {
            get {
                return ResourceManager.GetString("FormatHeading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 5.
        /// </summary>
        public static string FormatHeading5 {
            get {
                return ResourceManager.GetString("FormatHeading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 6.
        /// </summary>
        public static string FormatHeading6 {
            get {
                return ResourceManager.GetString("FormatHeading6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        public static string FormatParagraph {
            get {
                return ResourceManager.GetString("FormatParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string IsConnected {
            get {
                return ResourceManager.GetString("IsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string IsDisconnected {
            get {
                return ResourceManager.GetString("IsDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string LibraryImages {
            get {
                return ResourceManager.GetString("LibraryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palettes.
        /// </summary>
        public static string LibraryPalettes {
            get {
                return ResourceManager.GetString("LibraryPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string LibraryStyles {
            get {
                return ResourceManager.GetString("LibraryStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Expressive Web....
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string MenuCommunity {
            get {
                return ResourceManager.GetString("MenuCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string MenuFormat {
            get {
                return ResourceManager.GetString("MenuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string MenuInsert {
            get {
                return ResourceManager.GetString("MenuInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project....
        /// </summary>
        public static string MenuNewProject {
            get {
                return ResourceManager.GetString("MenuNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder....
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page....
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination project file:.
        /// </summary>
        public static string NewProjectFilePath {
            get {
                return ResourceManager.GetString("NewProjectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project using Kit:.
        /// </summary>
        public static string NewProjectKit {
            get {
                return ResourceManager.GetString("NewProjectKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online status.
        /// </summary>
        public static string OnlineStatus {
            get {
                return ResourceManager.GetString("OnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your website may require online resources to display properly. You can however tell the application to avoid resources downloading during your work..
        /// </summary>
        public static string OnlineStatusDescription {
            get {
                return ResourceManager.GetString("OnlineStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force offline mode.
        /// </summary>
        public static string OnlineStatusOfflineRequired {
            get {
                return ResourceManager.GetString("OnlineStatusOfflineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string PageFileName {
            get {
                return ResourceManager.GetString("PageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page template.
        /// </summary>
        public static string PageTemplate {
            get {
                return ResourceManager.GetString("PageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select parent.
        /// </summary>
        public static string SelectParentElement {
            get {
                return ResourceManager.GetString("SelectParentElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string StatusSaved {
            get {
                return ResourceManager.GetString("StatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string StatusSaving {
            get {
                return ResourceManager.GetString("StatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Click once** on objects to select. **Double click** to edit compatible objects..
        /// </summary>
        public static string StatusSelectMessage {
            get {
                return ResourceManager.GetString("StatusSelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new page....
        /// </summary>
        public static string TitleCreatePage {
            get {
                return ResourceManager.GetString("TitleCreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project....
        /// </summary>
        public static string TitleCreateProject {
            get {
                return ResourceManager.GetString("TitleCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems to take a bit more time, please wait....
        /// </summary>
        public static string VariableDurationActionMessage {
            get {
                return ResourceManager.GetString("VariableDurationActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter commands....
        /// </summary>
        public static string WatermarkFilterCommands {
            get {
                return ResourceManager.GetString("WatermarkFilterCommands", resourceCulture);
            }
        }
    }
}
